#general
EMPTY = -1
EMPTY_COORDS = (-1, -1)

#gate types
I_GATE = 0
H_GATE = 1
X_GATE = 2
Y_GATE = 3
Z_GATE = 4
T_GATE = 5
CONTROL = 100 #indicate taken spot by control

#game display variables
GAME_MAX_QBITS = 2
GAME_MAX_GATES = 14

WINDOW_SIZE_HEIGHT = 750
WINDOW_SIZE_WIDTH = 1000
GAME_WINDOW_TITLE = "Q-Chess Game"

QBIT_HEIGHT = [340, 410]

PRESET_FRAMERATE = 60

GATE_WIDTH_FULL = 50
GATE_WIDTH_HALF = 25
GATE_HEIGHT_HALF = 25
GATE_DIST = 20

CONTROL_CIRCLE_SIZE = 10
FONT_SIZE = 20
E_FONT_SIZE = 40

PLAYER_TURN_DISPLAY_X = 30
PLAYER_TURN_DISPLAY_Y = 20
PLAYER_ZERO_MESSAGE = "Turn: PLAYER ZERO"
PLAYER_ONE_MESSAGE = "Turn: PLAYER ONE"

LIVES_DISPLAY_X = 30
LIVES_DISPLAY_Y = 120
LIVES_DISPLAY_DROP = 40
LIVES_MESSAGE = "LIVES"
PLAYER_ZERO = "PLAYER ZERO"
PLAYER_ONE = "PLAYER ONE"

PLAYER_ONE_VICTORY = "PLAYER ONE WINS!!!"
PLAYER_ZERO_VICTORY = "PLAYER ZERO WINS!!!"
TIE_DEFEAT = "BOTH PLAYERS LOSE!!!"
END_MESSAGE_OFFSET_X = 200
END_MESSAGE_OFFSET_Y = 50

#game control variables
CYCLES_PER_PRESS = 5 #small as to account for rapid clicking

#game variables
SHOTS_IN_SIM = 30
LIVES_PER_SHOT = 10

#colors
WHITE = (255, 255, 255)
OFF_WHITE = (225, 225, 225)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
TEAL = (0, 255, 255)
PURPLE = (255, 0, 255)
YELLOW = (255, 255, 0)
